title: Youngsuk's website
author: Youngsuk Kim
email: ykim837@gatech.edu
timezone: 'America/New_York'
github_username:  JOE1994

show_downloads: false
show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
