title: Youngsuk Kim
author: Youngsuk Kim
email: joseph942010@gmail.com
timezone: 'America/New_York'
github_username:  JOE1994

show_downloads: false
show_excerpts: false # set to false to remove excerpts on the homepage
