title: Yet another blog on the web
author: Youngsuk Kim
email: ykim837@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
  Collection of regular writings of what I've learned so far.
# social links
github_username:  JOE1994

show_excerpts: true # set to false to remove excerpts on the homepage

timezone: 'America/New_York'

theme: jekyll-theme-dinky
