#!/c/Users/Public/anaconda3/envs/py37/python

import datetime
import json
import os
import sys

def is_valid_date_str(date_str: str) -> bool:
    try:
        datetime.datetime.strptime(date_str, '%Y-%m-%d')
        return True
    except ValueError:
        return False

def read_json_into_dict(filename: str) -> dict:
    assert(filename.endswith('.json'))
    json_as_dict = None
    with open(filename) as json_file:
        json_as_dict = json.load(json_file)
    return json_as_dict

def gen_front_matter(date_str: str) -> str:
    # Generate Front matter (for Jekyll)
    return (
        '---\n'
        'layout: workout_diary\n'
        f'date: {date_str}\n'
        '---\n\n'
        # Below are just Jekyll Liquid comments
        '{% comment %}\n'
        f'    This file was auto-generated by `json2md.py` from `{date_str}.json`\n'
        '{% endcomment %}\n\n'
    )

def gen_markdown_table(workout_dict: dict) -> str:
    markdown_str = (
        '|  | Weight (lbs) | Set1 | Set2 | Set3 | Set4 | Set5 | Set6 | Set7 | Set8 | Set9 | Set10 | Set11 | Set12 |\n'
        '|--|--------------|------|------|------|------|------|------|------|------|------|-------|-------|-------|\n'
    )
    row_fmt = '| {task} | {weight_in_lbs} | {s1} | {s2} | {s3} | {s4} | {s5} | {s6} | {s7} | {s8} | {s9} | {s10} | {s11} | {s12} |\n'

    for task in workout_dict:
        # Extend list to fit length 12
        workout_dict[task]['cnt'] += ['' for _ in range(12 - len(workout_dict[task]['cnt']))]
        # Append row to table
        markdown_str += row_fmt.format(
            task          = task,
            weight_in_lbs = workout_dict[task]['weight'] if 'weight' in workout_dict[task] else '',
            s1            = workout_dict[task]['cnt'][0],
            s2            = workout_dict[task]['cnt'][1],
            s3            = workout_dict[task]['cnt'][2],
            s4            = workout_dict[task]['cnt'][3],
            s5            = workout_dict[task]['cnt'][4],
            s6            = workout_dict[task]['cnt'][5],
            s7            = workout_dict[task]['cnt'][6],
            s8            = workout_dict[task]['cnt'][7],
            s9            = workout_dict[task]['cnt'][8],
            s10           = workout_dict[task]['cnt'][9],
            s11           = workout_dict[task]['cnt'][10],
            s12           = workout_dict[task]['cnt'][11]
        )

    return markdown_str

def gen_markdown(date_str: str, workout_dict: dict) -> str:
    return gen_front_matter(date_str) + gen_markdown_table(workout_dict)

if __name__ == '__main__':
    if not os.getcwd().endswith("workout_diary_challenge"):
        sys.exit('This script must be run at `JOE1994.github.io/workout_diary_challenge`')

    for i in range(1, len(sys.argv)):
        date_str = os.path.basename(sys.argv[i])[:-5]
        assert(is_valid_date_str(date_str))
        workout_dict = read_json_into_dict(sys.argv[i])

        markdown_str = gen_markdown(date_str, workout_dict)

        with open('data/markdown/' + date_str + '.md', 'w') as markdown_f:
            markdown_f.write(markdown_str)
        
        print(f'[info] Generated markdown from `{date_str}.json`\n')
